### ISSUE TITLE
第一周作业

### ISSUE THREAD

**Issue by abcxuhang** [algorithm014-algorithm014/algorithm014-algorithm014#14]
#学号:G20200343110020
#姓名:xh
#班级:14期1组
#语言:java
#作业&总结链接:https://github.com/abcxuhang/algorithm014-algorithm014/tree/master/Week_01

**Comment by GeekUniversity** [comment]
> #学号:G20200343110020
> #姓名:xh
> #班级:14期1组
> #语言:java
> #作业&总结链接:https://github.com/abcxuhang/algorithm014-algorithm014/tree/master/Week_01

亲 你的作业交错地方啦 要交Week 01 作业链接合集👈作业交这里 不是新建issues
