### ISSUE TITLE
week1

### ISSUE THREAD

**Issue by zhouzongbo** [algorithm014-algorithm014/algorithm014-algorithm014#3]
#学号: G20200343110051
#姓名: 周宗波
#班级: 14期1班1组
#语言: Java
#作业&总结链接: https://github.com/zhouzongbo/algorithm014-algorithm014/tree/master/Week_01

**Comment by lumax2** [comment]
#学号: G20200343110032
#姓名: 程浩
#班级: 14期2班1组
#语言: Java
#作业&总结链接: https://github.com/lumax2/algorithm014-algorithm014/tree/master/Week_01

**Comment by GeekUniversity** [comment]
> #学号: G20200343110051
> #姓名: 周宗波
> #班级: 14期1班1组
> #语言: Java
> #作业&总结链接: https://github.com/zhouzongbo/algorithm014-algorithm014/tree/master/Week_01

亲 你的作业交错地方啦 要放到班班建立的 Week 01 作业链接合集👈作业交这里那里
